import React, { useEffect, useRef, useState } from "react";
import {
  Button,
  Input,
  InputNumber,
  Select,
  DatePicker,
  Switch,
  TimePicker,
  ColorPicker,
  Checkbox,
  Radio,
  Slider,
  Upload,
  Toast,
  Modal,
  Tooltip,
  NxPlus,
  NxTrash,
  NxUpload,
  NxFolder,
  NxFileText,
  NxEye,
  NxX,
  Spin,
  NxRefreshCw,
} from "@nexgensis/core";
const { TextArea } = Input;
import dayjs from "dayjs";
import SignatureCanvas from "react-signature-canvas";
import ReactQuill from "react-quill-new";
import "react-quill-new/dist/quill.snow.css";
import Axios from "axios";
import { baseUrl } from "@/utils/apiConfig";
import { upload_document } from "@/apps/DMSApp/dms/lib/api";
import AttachmentModalWrapper from "@/apps/DMSApp/dms/components/AttachmentModalWrapper";

const { RangePicker } = DatePicker;
const { Group: CheckboxGroup } = Checkbox;
const { Group: RadioGroup } = Radio;


const TableViewer = ({ field, formik }) => {
  const { values, setFieldValue } = formik;
  const tableData = values[field.name] || [];
  const initializedRef = useRef(false);
  const signatureRefs = useRef({});

  // Safe access to columns - must be defined before hooks that use it
  const columns = field.fields || [];

  // State for dynamic options
  const [dynamicOptions, setDynamicOptions] = useState({});

  // State for row-specific dynamic options (for table column dependencies)
  const [rowDynamicOptions, setRowDynamicOptions] = useState({});
  // Structure: { "rowIndex_columnName_dependencyValue": [...options] }

  // State for section-level dependency options (shared across all rows)
  const [sectionDependencyOptions, setSectionDependencyOptions] = useState({});
  // Structure: { "columnName_dependencyValue": [...options] }

  // State for auto-generate loading per cell (key: "rowIndex_columnName")
  const [autoGenLoading, setAutoGenLoading] = useState({});
  const prevAutoGenDepsRef = useRef({});

  // Fetch auto-generated value for a table column cell
  const fetchAutoGeneratedValue = (column, rowIndex) => {
    if (!column.auto_generate_endpoint) return;

    let endpoint = column.auto_generate_endpoint;
    const mappings = column.auto_generate_mappings || {};

    for (const [placeholder, depFieldName] of Object.entries(mappings)) {
      if (!depFieldName) continue;

      // Check if dependency is another table column (same row) or a section-level field
      const isTableColumn = columns.some((col) => col.name === depFieldName);
      let depValue;
      if (isTableColumn) {
        const row = tableData[rowIndex];
        depValue = row ? row[depFieldName] : undefined;
      } else {
        depValue = values[depFieldName];
      }

      const resolved = depValue?.value || depValue || "";
      if (!resolved) return;
      endpoint = endpoint.replace(placeholder, encodeURIComponent(resolved));
    }

    const cellKey = `${rowIndex}_${column.name}`;
    setAutoGenLoading((prev) => ({ ...prev, [cellKey]: true }));

    Axios.get(`${baseUrl}${endpoint}`, {
      headers: {
        Authorization: `Bearer ${localStorage.getItem("Token")}`,
      },
    })
      .then((res) => {
        const data = res.data?.data || res.data;
        const value = data?.value || data?.name || (typeof data === "string" ? data : "");
        updateCell(rowIndex, column.name, value);
      })
      .catch((error) => {
        console.error("Auto-generate failed for table cell:", error);
      })
      .finally(() => {
        setAutoGenLoading((prev) => ({ ...prev, [cellKey]: false }));
      });
  };

  // State for text detail modal (view long content)
  const [textModal, setTextModal] = useState({
    open: false,
    title: "",
    value: "",
    rowIndex: null,
    columnName: null,
  });

  // State for upload source modal
  const [openUploadSourceModal, setOpenUploadSourceModal] = useState(false);
  const [openMinIOBrowserModal, setOpenMinIOBrowserModal] = useState(false);
  const [currentUploadField, setCurrentUploadField] = useState(null);
  // Structure: { rowIndex, columnName, isMultiple, columnType }

  // Helper function for API calls
  const get_function = (url, success, params = {}, signal = null) => {
    Axios.get(url, {
      params,
      signal,
      headers: {
        Authorization: `Bearer ${localStorage.getItem("Token")}`,
      },
    })
      .then((res) => {
        success(res);
      })
      .catch((error) => {
      });
  };

  // Fetch options for section-level dependencies (shared across all rows)
  const fetchSectionDependentOptions = async (column, dependencyValue) => {
    const { end_point, name } = column;

    // Guard: skip if no valid dependency value
    if (!dependencyValue) return;

    // Replace {id} with dependency value
    const processedEndpoint = end_point.replace("{id}", dependencyValue);

    // Guard: skip if {id} was not replaced (no valid value)
    if (processedEndpoint.includes("{id}")) return;

    // Create cache key (no row index for section-level dependencies)
    const cacheKey = `${name}_${dependencyValue}`;

    // Check if already fetched
    if (sectionDependencyOptions[cacheKey]) return;

    try {
      const response = await Axios.get(`${baseUrl}${processedEndpoint}`, {
        headers: {
          Authorization: `Bearer ${localStorage.getItem("Token")}`,
        },
      });

      const data = response.data.data || response.data;
      const options = data.map((item) => ({
        label: item.name,
        value: item.id,
      }));

      setSectionDependencyOptions(prev => ({
        ...prev,
        [cacheKey]: options
      }));
    } catch (error) {
      console.error(`Error fetching section-dependent options for ${name}:`, error);
    }
  };

  // Fetch options for row-specific dependencies (table column dependencies)
  const fetchRowDependentOptions = async (column, rowIndex, dependencyValue) => {
    const { end_point, name } = column;

    // Guard: skip if no valid dependency value
    if (!dependencyValue) return;

    // Replace {id} with dependency value
    const processedEndpoint = end_point.replace("{id}", dependencyValue);

    // Guard: skip if {id} was not replaced (no valid value)
    if (processedEndpoint.includes("{id}")) return;

    // Create cache key
    const cacheKey = `${rowIndex}_${name}_${dependencyValue}`;

    // Check if already fetched
    if (rowDynamicOptions[cacheKey]) return;

    try {
      const response = await Axios.get(`${baseUrl}${processedEndpoint}`, {
        headers: {
          Authorization: `Bearer ${localStorage.getItem("Token")}`,
        },
      });

      const data = response.data.data || response.data;
      const options = data.map((item) => ({
        label: item.name,
        value: item.id,
      }));

      setRowDynamicOptions(prev => ({
        ...prev,
        [cacheKey]: options
      }));
    } catch (error) {
      console.error(`Error fetching dependent options for ${name}:`, error);
    }
  };

  useEffect(() => {
  }, []);

  useEffect(() => {
    if (!columns.length) return; // Guard inside effect

    const controller = new AbortController();
    const allFields = columns;
    const tableSubfields = allFields
      .filter((f) => f.type === "table")
      .flatMap((table) => table.fields || []);

    const combinedFields = [...allFields, ...tableSubfields];

    combinedFields.forEach((f) => {
      // Skip fields with API dependencies or {id} placeholder - they will be fetched when dependency value is selected
      const hasApiDependency = f.validation?.apiDependency?.enabled;
      const hasPlaceholder = f.end_point && f.end_point.includes("{id}");

      if (f.dynamic && !hasApiDependency && !hasPlaceholder) {
        get_function(
          `${baseUrl}${f.end_point}`,
          (res) => {
            const data = res.data.data;
            const options = data.map((item) => ({
              label: item.name,
              value: item.id,
            }));
            // Use functional update to merge options properly
            setDynamicOptions((prev) => ({
              ...prev,
              [f.name]: options
            }));
          },
          {},
          controller.signal
        );
      }
    });

    return () => {
      controller.abort();
    };
  }, [field, columns]);

  useEffect(() => {
    if (
      !initializedRef.current &&
      (!values[field.name] || values[field.name].length === 0)
    ) {
      setFieldValue(field.name, field.defaultValues);
      initializedRef.current = true;
    }
  }, [field.name, field.defaultValues, setFieldValue, values]);

  // Helper to extract a usable value from various field shapes
  const extractDependencyValue = (raw) => {
    if (!raw) return null;
    if (typeof raw === 'object' && raw.value !== undefined) return raw.value;
    if (typeof raw === 'string' || typeof raw === 'number') return raw;
    return null;
  };

  // Collect the dependency field names once (stable across renders)
  const dependentColumns = columns.filter(col =>
    col.validation?.apiDependency?.enabled &&
    col.validation?.apiDependency?.dependsOn &&
    col.dynamic &&
    col.end_point &&
    col.end_point.includes("{id}")
  );

  // Build a stable key from only the section-level dependency values
  const sectionDepKey = dependentColumns
    .filter(col => !columns.some(c => c.name === col.validation.apiDependency.dependsOn))
    .map(col => {
      const v = extractDependencyValue(values[col.validation.apiDependency.dependsOn]);
      return `${col.name}:${v || ""}`;
    })
    .join("|");

  // Build a stable key from only the row-level dependency values
  const rowDepKey = dependentColumns
    .filter(col => columns.some(c => c.name === col.validation.apiDependency.dependsOn))
    .map(col => {
      return tableData.map((row, i) => {
        const v = extractDependencyValue(row[col.validation.apiDependency.dependsOn]);
        return `${i}_${col.name}:${v || ""}`;
      }).join(",");
    })
    .join("|");

  // Fetch dependent options only when actual dependency values change
  useEffect(() => {
    if (!dependentColumns.length) return;

    // Handle columns that depend on section-level fields (not row-specific)
    dependentColumns.forEach(column => {
      const dependencyFieldName = column.validation.apiDependency.dependsOn;
      const isTableColumnDependency = columns.some(col => col.name === dependencyFieldName);

      if (!isTableColumnDependency) {
        const valueToUse = extractDependencyValue(values[dependencyFieldName]);
        if (valueToUse) {
          fetchSectionDependentOptions(column, valueToUse);
        }
      }
    });

    // Handle columns that depend on other table columns (row-specific)
    if (tableData.length > 0) {
      tableData.forEach((row, rowIndex) => {
        dependentColumns.forEach(column => {
          const dependencyFieldName = column.validation.apiDependency.dependsOn;
          const isTableColumnDependency = columns.some(col => col.name === dependencyFieldName);

          if (isTableColumnDependency) {
            const valueToUse = extractDependencyValue(row[dependencyFieldName]);
            if (valueToUse) {
              fetchRowDependentOptions(column, rowIndex, valueToUse);
            }
          }
        });
      });
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [sectionDepKey, rowDepKey]);

  // Auto-generate trigger effect for table columns
  useEffect(() => {
    if (!columns.length || !tableData.length) return;

    const autoGenColumns = columns.filter(
      (col) => col.auto_generate && col.auto_generate_endpoint && col.auto_generate_mappings && Object.keys(col.auto_generate_mappings).length > 0
    );

    if (!autoGenColumns.length) return;

    autoGenColumns.forEach((column) => {
      const mappedFieldNames = Object.values(column.auto_generate_mappings).filter(Boolean);
      if (mappedFieldNames.length === 0) return;

      tableData.forEach((row, rowIndex) => {
        // Build a combined key from all dependent field values
        const depValues = mappedFieldNames.map((name) => {
          const isTableColumn = columns.some((col) => col.name === name);
          if (isTableColumn) {
            const val = row[name];
            return val?.value || val || "";
          } else {
            const val = values[name];
            return val?.value || val || "";
          }
        });

        // All dependent fields must have values before triggering
        if (depValues.some((v) => !v)) return;

        const currentKey = depValues.join("|");
        const depKey = `${rowIndex}_${column.name}`;
        const prevKey = prevAutoGenDepsRef.current[depKey];

        if (currentKey !== prevKey) {
          prevAutoGenDepsRef.current[depKey] = currentKey;
          fetchAutoGeneratedValue(column, rowIndex);
        }
      });
    });
  }, [tableData, columns, values]);

  // Early return AFTER all hooks
  if (!columns.length) {
    return (
      <div
        style={{
          border: "1px dashed #d9d9d9",
          borderRadius: "6px",
          padding: "24px",
          textAlign: "center",
          color: "#999",
        }}
      >
        No table columns configured for this field.
      </div>
    );
  }

  // File upload handler for table cells - uploads to DMS
  const handleFileUpload = async (
    file,
    rowIndex,
    columnName,
    isMultiple = false
  ) => {
    try {
      // Create FormData for DMS upload
      const formData = new FormData();
      formData.append("file", file);
      formData.append("tag", "Form");
      formData.append("name", file.name || "");
      formData.append("file_type", file.type);

      // Upload to DMS
      await upload_document(
        formData,
        (res) => {
          if (res.status === "success") {
            const fileObj = {
              file_id: res.data?.file_id || res.file_id || Date.now().toString(),
              file_name: file.name,
              file_type: file.type,
              file_size: file.size,
              file_url: res.data?.file_url || res.file_url,
            };

            const currentValue = getCellValue(rowIndex, columnName);

            if (isMultiple) {
              const currentFiles = Array.isArray(currentValue) ? currentValue : [];
              updateCell(rowIndex, columnName, [...currentFiles, fileObj]);
            } else {
              updateCell(rowIndex, columnName, fileObj);
            }

            Toast.success("File uploaded successfully!");
          } else {
            Toast.error(res.message || "Error uploading file");
          }
        },
        (error) => {
          console.error("DMS upload error:", error);
          Toast.error("Error uploading file to DMS");
        }
      );

      return false; // Prevent default upload
    } catch (error) {
      console.error("File upload error:", error);
      Toast.error("Error uploading file");
      return false;
    }
  };

  // Handle local file upload from modal
  const handleLocalUpload = () => {
    setOpenUploadSourceModal(false);

    if (!currentUploadField) return;

    const { rowIndex, columnName, isMultiple, columnType } = currentUploadField;

    // Create a hidden file input and trigger it
    const input = document.createElement("input");
    input.type = "file";
    input.multiple = isMultiple || false;
    input.accept = columnType === "image" ? "image/*" : undefined;

    input.onchange = (e) => {
      const files = Array.from(e.target.files);
      if (files.length > 0) {
        if (!isMultiple) {
          handleFileUpload(files[0], rowIndex, columnName, false);
        } else {
          files.forEach((file) => {
            handleFileUpload(file, rowIndex, columnName, true);
          });
        }
      }
    };

    input.click();
  };

  // Handle MinIO/DMS file selection
  const handleMinIOUpload = () => {
    setOpenUploadSourceModal(false);
    setOpenMinIOBrowserModal(true);
  };

  // Handle file selection from MinIO/DMS browser
  const handleMinIOFileSelect = (selectedFiles) => {
    setOpenMinIOBrowserModal(false);

    if (!currentUploadField) return;

    const { rowIndex, columnName, isMultiple } = currentUploadField;
    const files = Array.isArray(selectedFiles) ? selectedFiles : [selectedFiles];

    const transformFile = (file) => ({
      file_id: file.id,
      file_type: file.mime_type,
      file_name: file.name,
      file_size: file.size,
      file_url: file.url,
    });

    if (isMultiple) {
      const currentValue = getCellValue(rowIndex, columnName);
      const currentFiles = Array.isArray(currentValue) ? currentValue : [];
      const newFiles = files.map(transformFile);
      updateCell(rowIndex, columnName, [...currentFiles, ...newFiles]);
    } else {
      updateCell(rowIndex, columnName, transformFile(files[0]));
    }

    setCurrentUploadField(null);
    Toast.success("File(s) selected successfully!");
  };

  // File preview component for table cells
  const FilePreview = ({ file, onRemove, isImage = false }) => {
    const handlePreview = () => {
      if (file.file_url) {
        window.open(file.file_url, "_blank");
      }
    };

    // Format file size
    const formatFileSize = (bytes) => {
      if (!bytes) return "0 KB";
      if (bytes < 1024) return `${bytes} B`;
      if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
      return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
    };

    return (
      <div
        style={{
          display: "flex",
          alignItems: "center",
          padding: "8px 10px",
          backgroundColor: "#f8fafc",
          border: "1px solid #e2e8f0",
          borderRadius: "6px",
          marginBottom: "6px",
          gap: "10px",
        }}
      >
        {/* File Icon or Image Preview */}
        <div
          style={{
            width: "32px",
            height: "32px",
            borderRadius: "4px",
            backgroundColor: isImage ? "transparent" : "#e0f2fe",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            flexShrink: 0,
          }}
        >
          {isImage && file.file_url ? (
            <img
              src={file.file_url}
              alt={file.file_name}
              style={{
                width: "32px",
                height: "32px",
                objectFit: "cover",
                borderRadius: "4px",
              }}
            />
          ) : (
            <NxFileText style={{ fontSize: "16px", color: "#0284c7" }} />
          )}
        </div>

        {/* File Info */}
        <div style={{ flex: 1, minWidth: 0 }}>
          <Tooltip title={file.file_name}>
            <div
              style={{
                fontWeight: 500,
                fontSize: "12px",
                color: "#334155",
                overflow: "hidden",
                textOverflow: "ellipsis",
                whiteSpace: "nowrap",
                maxWidth: "120px",
              }}
            >
              {file.file_name}
            </div>
          </Tooltip>
          <div style={{ fontSize: "11px", color: "#94a3b8" }}>
            {formatFileSize(file.file_size)}
          </div>
        </div>

        {/* Action Buttons */}
        <div style={{ display: "flex", gap: "4px", flexShrink: 0 }}>
          <Tooltip title="View">
            <Button
              type="text"
              size="small"
              icon={<NxEye style={{ fontSize: "14px" }} />}
              onClick={handlePreview}
              disabled={!file.file_url}
              style={{
                width: "28px",
                height: "28px",
                padding: 0,
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                color: "#0284c7",
                border: "1px solid #e2e8f0",
                borderRadius: "4px",
              }}
            />
          </Tooltip>
          <Tooltip title="Remove">
            <Button
              type="text"
              size="small"
              danger
              icon={<NxX style={{ fontSize: "14px" }} />}
              onClick={onRemove}
              style={{
                width: "28px",
                height: "28px",
                padding: 0,
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                border: "1px solid #fecaca",
                borderRadius: "4px",
                backgroundColor: "#fef2f2",
              }}
            />
          </Tooltip>
        </div>
      </div>
    );
  };

  const getInitialValue = (column) => {
    switch (column.type) {
      case "multi_text":
        return column.value || [];
      case "checkbox":
        return column.value || [];
      case "switch":
        return column.value !== null ? column.value : false;
      case "number":
      case "range":
        return column.value !== null ? Number(column.value) : 0;
      case "select":
        if (column.validation?.isMultiple) {
          return column.value || [];
        }
        return column.value !== null ? column.value : undefined;
      case "radio":
        return column.value || "";
      case "file":
      case "image":
        return column.validation?.isMultiple
          ? column.value || []
          : column.value || null;
      case "date":
        return column.value || "";
      case "time":
        return column.value || "";
      case "date_range":
      case "time_range":
        return column.value || [];
      case "color":
        return column.value || "#1677ff";
      case "signature":
        return column.value || "";
      case "richtext":
        return column.value || "";
      case "textarea":
        return column.value || "";
      case "email":
      case "password":
        return column.value || "";
      case "table":
        return field.defaultValues && field.defaultValues.length > 0
          ? field.defaultValues
          : [];
      default:
        return column.value !== null ? column.value : "";
    }
  };

  // Use column.name as key to match API data format
  const addRow = () => {
    const newRow = columns.reduce((acc, column) => {
      // Use column.name to match API data structure
      acc[column.name] = getInitialValue(column);
      return acc;
    }, {});
    setFieldValue(field.name, [...tableData, newRow]);
  };

  const deleteRow = (rowIndex) => {
    const newData = tableData.filter((_, index) => index !== rowIndex);
    setFieldValue(field.name, newData);
  };

  const updateCell = (rowIndex, columnName, value) => {
    const newData = [...tableData];
    if (!newData[rowIndex]) {
      newData[rowIndex] = {};
    }

    const column = columns.find((f) => f.name === columnName);
    if (column) {
      // Use column.name as the key to match API data structure
      const key = column.name;
      switch (column.type) {
        case "multi_text":
          newData[rowIndex][key] = Array.isArray(value) ? value : [];
          break;
        case "text":
        case "email":
        case "password":
        case "textarea":
        case "richtext":
          newData[rowIndex][key] =
            value !== null && value !== undefined ? value : "";
          break;
        case "number":
        case "range":
          newData[rowIndex][key] =
            value !== null && value !== undefined ? value : 0;
          break;
        case "select":
          if (column.validation?.isMultiple) {
            newData[rowIndex][key] = Array.isArray(value) ? value : [];
          } else {
            newData[rowIndex][key] =
              value !== undefined ? value : undefined;
          }
          break;
        case "radio":
          newData[rowIndex][key] =
            value !== null && value !== undefined ? value : "";
          break;
        case "checkbox":
          newData[rowIndex][key] = Array.isArray(value) ? value : [];
          break;
        case "date":
        case "time":
          newData[rowIndex][key] =
            value !== null && value !== undefined ? value : "";
          break;
        case "date_range":
        case "time_range":
          newData[rowIndex][key] = Array.isArray(value) ? value : [];
          break;
        case "switch":
          newData[rowIndex][key] = Boolean(value);
          break;
        case "color":
          newData[rowIndex][key] =
            value !== null && value !== undefined ? value : "#1677ff";
          break;
        case "file":
        case "image":
          if (column.validation?.isMultiple) {
            newData[rowIndex][key] = Array.isArray(value) ? value : [];
          } else {
            newData[rowIndex][key] = value;
          }
          break;
        case "signature":
          newData[rowIndex][key] =
            value !== null && value !== undefined ? value : "";
          break;
        default:
          newData[rowIndex][key] = value;
      }
    } else {
      newData[rowIndex][columnName] = value;
    }

    // Check if any columns depend on this field
    const dependentColumns = columns.filter(col =>
      col.validation?.apiDependency?.enabled &&
      col.validation?.apiDependency?.dependsOn === columnName
    );

    if (dependentColumns.length > 0) {
      // Clear values of dependent columns
      dependentColumns.forEach(depCol => {
        newData[rowIndex][depCol.name] = undefined;

        // Clear cached options for this row's dependent columns
        setRowDynamicOptions(prev => {
          const updated = { ...prev };
          Object.keys(updated).forEach(key => {
            if (key.startsWith(`${rowIndex}_${depCol.name}_`)) {
              delete updated[key];
            }
          });
          return updated;
        });
      });
    }

      // When the value is cleared, also clear auto-generate columns that map to this field
    const isValueCleared = value === null || value === undefined || value === "";
    if (isValueCleared) {
      const autoGenDependentColumns = columns?.filter(col =>
        col.auto_generate &&
        col.auto_generate_mappings &&
        Object.values(col.auto_generate_mappings)?.includes(columnName)
      );
      autoGenDependentColumns.forEach(depCol => {
        newData[rowIndex][depCol.name] = undefined;
        // Reset the auto-gen dep key so it can re-trigger if a new value is selected
        const depKey = `${rowIndex}_${depCol.name}`;
        delete prevAutoGenDepsRef.current[depKey];
      });
    }

    setFieldValue(field.name, newData);
  };

  const getCellValue = (rowIndex, columnName) => {
    const rowData = tableData[rowIndex];
    if (!rowData) return undefined;

    const column = columns.find((f) => f.name === columnName);
    // Use column.name as the primary key (API data format), fallback to column.label for backward compatibility
    const primaryKey = column ? column.name : columnName;
    const fallbackKey = column ? column.label : columnName;
    // Check primary key first, then fallback
    const cellValue = rowData[primaryKey] !== undefined ? rowData[primaryKey] : rowData[fallbackKey];

    if (!column) return cellValue;

    switch (column.type) {
      case "multi_text":
        return Array.isArray(cellValue) ? cellValue : [];
      case "text":
      case "email":
      case "password":
      case "textarea":
        return cellValue !== undefined && cellValue !== null ? cellValue : "";
      case "number":
      case "range":
        return cellValue !== undefined && cellValue !== null ? cellValue : 0;
      case "select":
        if (column.validation?.isMultiple) {
          return Array.isArray(cellValue) ? cellValue : [];
        }
        return cellValue !== undefined ? cellValue : undefined;
      case "radio":
        return cellValue !== undefined && cellValue !== null ? cellValue : "";
      case "checkbox":
        return Array.isArray(cellValue) ? cellValue : [];
      case "date":
      case "time":
        return cellValue !== undefined && cellValue !== null ? cellValue : "";
      case "date_range":
      case "time_range":
        return Array.isArray(cellValue) ? cellValue : [];
      case "switch":
        return cellValue !== undefined && cellValue !== null
          ? cellValue
          : false;
      case "color":
        return cellValue !== undefined && cellValue !== null
          ? cellValue
          : "#1677ff";
      case "file":
      case "image":
        if (column.validation?.isMultiple) {
          return Array.isArray(cellValue) ? cellValue : [];
        }
        return cellValue || null;
      case "signature":
      case "richtext":
        return cellValue !== undefined && cellValue !== null ? cellValue : "";
      default:
        return cellValue;
    }
  };

  const renderCell = (column, rowIndex) => {
    const value = getCellValue(rowIndex, column.name);
    const cellKey = `${rowIndex}-${column.name}`;

    const cellStyle = {
      width: "100%",
      border: "none",
      outline: "none",
      backgroundColor: "transparent",
      fontSize: "12px",
    };

    // Threshold for showing expand button (characters)
    const TEXT_TRUNCATE_LIMIT = 100;

    switch (column.type) {
      case "multi_text":
        return (
          <div key={cellKey} className="multi-text-vertical" style={{ minWidth: "150px" }}>
            <style>{`
              .multi-text-vertical .ant-select-selector {
                flex-direction: column !important;
                align-items: flex-start !important;
              }
              .multi-text-vertical .ant-select-selection-overflow {
                flex-direction: column !important;
                align-items: flex-start !important;
                gap: 4px !important;
              }
              .multi-text-vertical .ant-select-selection-overflow-item {
                width: 100% !important;
              }
            `}</style>
            <Select
              mode="tags"
              open={false}
              style={{ width: "100%" }}
              placeholder={`Enter ${column.label?.toLowerCase() || "values"}`}
              value={Array.isArray(value) ? value : []}
              onChange={(val) => updateCell(rowIndex, column.name, val)}
              tokenSeparators={[","]}
              variant="borderless"
              size="small"
              suffixIcon={null}
            />
          </div>
        );
      case "text": {
        if (column.auto_generate && column.auto_generate_endpoint) {
          const hasDependency = column.auto_generate_mappings && Object.values(column.auto_generate_mappings).some(Boolean);
          const loadingKey = `${rowIndex}_${column.name}`;
          const isUrl = value && typeof value === "string" && /^https?:\/\//i.test(value);

          if (isUrl) {
            return (
              <div key={cellKey} style={{ display: "flex", alignItems: "center", padding: "0 8px", width: "100%" }}>
                <a
                  href={value}
                  target="_blank"
                  rel="noopener noreferrer"
                  title={value}
                  style={{
                    fontSize: "12px",
                    color: "#1677ff",
                    textDecoration: "none",
                    overflow: "hidden",
                    textOverflow: "ellipsis",
                    whiteSpace: "nowrap",
                    flex: 1,
                  }}
                  onMouseEnter={(e) => (e.target.style.textDecoration = "underline")}
                  onMouseLeave={(e) => (e.target.style.textDecoration = "none")}
                >
                  View Document
                </a>
                {!hasDependency && (
                  <Button
                    type="text"
                    size="small"
                    loading={autoGenLoading[loadingKey]}
                    icon={!autoGenLoading[loadingKey] ? <NxRefreshCw size={14} /> : null}
                    onClick={() => fetchAutoGeneratedValue(column, rowIndex)}
                    disabled={autoGenLoading[loadingKey]}
                    style={{ border: "none", padding: 0, height: "auto", flexShrink: 0 }}
                  />
                )}
              </div>
            );
          }

          return (
            <Input
              key={cellKey}
              value={value || ""}
              placeholder={`${column.label}`}
              readOnly
              variant="borderless"
              style={{ ...cellStyle, backgroundColor: "#f5f5f5", color: "#595959", cursor: "default" }}
              size="small"
              suffix={
                hasDependency
                  ? (autoGenLoading[loadingKey] ? <Spin size="small" /> : null)
                  : (
                    <Button
                      type="text"
                      size="small"
                      loading={autoGenLoading[loadingKey]}
                      icon={!autoGenLoading[loadingKey] ? <NxRefreshCw size={14} /> : null}
                      onClick={() => fetchAutoGeneratedValue(column, rowIndex)}
                      disabled={autoGenLoading[loadingKey]}
                      style={{ border: "none", padding: 0, height: "auto" }}
                    />
                  )
              }
            />
          );
        }
        return (
          <div key={cellKey} style={{ display: "flex", alignItems: "flex-start", gap: "2px", width: "100%" }}>
            <TextArea
              value={value || ""}
              onChange={(e) => updateCell(rowIndex, column.name, e.target.value)}
              placeholder={`Enter ${column.label?.toLowerCase()}`}
              variant="borderless"
              style={cellStyle}
              rows={1}
              autoSize={{ minRows: 1, maxRows: 2 }}
            />
            {String(value || "").length > TEXT_TRUNCATE_LIMIT && (
              <Tooltip title="Expand">
                <Button
                  type="text"
                  size="small"
                  icon={<NxEye style={{ fontSize: "13px" }} />}
                  style={{ flexShrink: 0, color: "#3b82f6", marginTop: "2px" }}
                  onClick={() => setTextModal({ open: true, title: column.label, value: value || "", rowIndex, columnName: column.name })}
                />
              </Tooltip>
            )}
          </div>
        );
      }

      case "email":
        return (
          <Input
            key={cellKey}
            type="email"
            value={value || ""}
            onChange={(e) => updateCell(rowIndex, column.name, e.target.value)}
            placeholder={`Enter ${column.label?.toLowerCase()}`}
            variant="borderless"
            style={cellStyle}
            size="small"
          />
        );

      case "password":
        return (
          <Input.Password
            key={cellKey}
            value={value || ""}
            onChange={(e) => updateCell(rowIndex, column.name, e.target.value)}
            placeholder={`Enter ${column.label?.toLowerCase()}`}
            variant="borderless"
            style={cellStyle}
            size="small"
          />
        );

      case "number": {
        if (column.auto_generate && column.auto_generate_endpoint) {
          const hasDependency = column.auto_generate_mappings && Object.values(column.auto_generate_mappings).some(Boolean);
          const loadingKey = `${rowIndex}_${column.name}`;
          return (
            <Input
              key={cellKey}
              value={value || ""}
              placeholder={`${column.label}`}
              readOnly
              variant="borderless"
              style={{ ...cellStyle, backgroundColor: "#f5f5f5", color: "#595959", cursor: "default" }}
              size="small"
              suffix={
                hasDependency
                  ? (autoGenLoading[loadingKey] ? <Spin size="small" /> : null)
                  : (
                    <Button
                      type="text"
                      size="small"
                      loading={autoGenLoading[loadingKey]}
                      icon={!autoGenLoading[loadingKey] ? <NxRefreshCw size={14} /> : null}
                      onClick={() => fetchAutoGeneratedValue(column, rowIndex)}
                      disabled={autoGenLoading[loadingKey]}
                      style={{ border: "none", padding: 0, height: "auto" }}
                    />
                  )
              }
            />
          );
        }
        return (
          <InputNumber
            key={cellKey}
            style={{ width: "100%" }}
            value={value === "" ? undefined : value}
            onChange={(val) =>
              updateCell(rowIndex, column.name, val === null ? "" : val)
            }
            placeholder={column.label}
            variant="borderless"
            size="small"
            controls={false}
          />
        );
      }

      case "textarea":
        return (
          <div key={cellKey} style={{ display: "flex", alignItems: "flex-start", gap: "2px", width: "100%" }}>
            <TextArea
              value={value || ""}
              onChange={(e) => updateCell(rowIndex, column.name, e.target.value)}
              placeholder={`Enter ${column.label?.toLowerCase()}`}
              variant="borderless"
              style={cellStyle}
              rows={1}
              autoSize={{ minRows: 1, maxRows: 2 }}
            />
            {String(value || "").length > TEXT_TRUNCATE_LIMIT && (
              <Tooltip title="Expand">
                <Button
                  type="text"
                  size="small"
                  icon={<NxEye style={{ fontSize: "13px" }} />}
                  style={{ flexShrink: 0, color: "#3b82f6", marginTop: "2px" }}
                  onClick={() => setTextModal({ open: true, title: column.label, value: value || "", rowIndex, columnName: column.name })}
                />
              </Tooltip>
            )}
          </div>
        );

      case "select": {
        let options = [];
        let isDisabled = false;
        let placeholder = column.label;

        // Check if this column has API dependency
        const apiDep = column.validation?.apiDependency;
        if (apiDep?.enabled && apiDep.dependsOn) {
          const dependencyFieldName = apiDep.dependsOn;

          // Check if dependency is a table column or section-level field
          const isTableColumnDependency = columns.some(col => col.name === dependencyFieldName);

          let dependencyValue;
          if (isTableColumnDependency) {
            // Get from table row data
            dependencyValue = getCellValue(rowIndex, dependencyFieldName);
          } else {
            // Get from section-level form values
            dependencyValue = values[dependencyFieldName];
          }

          let valueToUse = null;
          if (dependencyValue) {
            if (typeof dependencyValue === 'object' && dependencyValue.value !== undefined) {
              valueToUse = dependencyValue.value;
            } else if (typeof dependencyValue === 'string' || typeof dependencyValue === 'number') {
              valueToUse = dependencyValue;
            }
          }

          if (valueToUse) {
            // Use different cache based on dependency type
            if (isTableColumnDependency) {
              // Row-specific options for table column dependencies
              const cacheKey = `${rowIndex}_${column.name}_${valueToUse}`;
              options = rowDynamicOptions[cacheKey] || [];
            } else {
              // Shared options for section-level dependencies
              const cacheKey = `${column.name}_${valueToUse}`;
              options = sectionDependencyOptions[cacheKey] || [];
            }
          } else {
            isDisabled = true;
            placeholder = `Select ${apiDep.dependsOn} first`;
          }
        } else {
          // Use global dynamic options or static options
          options = dynamicOptions[column.name] ||
                    (column.options || []).map((opt) => ({
                      label: opt ? opt.label ?? opt : "",
                      value: opt ? opt.value ?? opt : "",
                    }));
        }

        return (
          <Select
            key={cellKey}
            mode={column.validation?.isMultiple ? "multiple" : undefined}
            value={
              column.validation?.isMultiple
                ? value?.map((i) => i.value) || []
                : value?.value || null
            }
            onChange={(val, opt) => {
              if (opt) updateCell(rowIndex, column.name, opt);
              else
                updateCell(
                  rowIndex,
                  column.name,
                  column.validation?.isMultiple ? [] : null
                );
            }}
            placeholder={placeholder}
            variant="borderless"
            style={{ width: "100%" }}
            size="small"
            showSearch={true}
            allowClear={true}
            maxCount={parseInt(column.validation?.maxSelection)}
            options={options}
            disabled={isDisabled}
            filterOption={(input, option) =>
              (option?.label ?? '').toLowerCase().includes(input.toLowerCase())
            }
            optionRender={(option) => (
              <div style={{
                whiteSpace: 'normal',
                wordWrap: 'break-word',
                padding: '4px 0'
              }}>
                {option.label}
              </div>
            )}
          />
        );
      }

      case "radio":
        return (
          <RadioGroup
            key={cellKey}
            value={value}
            onChange={(e) => updateCell(rowIndex, column.name, e.target.value)}
            size="small"
          >
            {column.options?.map((opt) => (
              <Radio key={opt} value={opt} style={{ fontSize: "12px" }}>
                {opt}
              </Radio>
            ))}
          </RadioGroup>
        );

      case "checkbox":
        return (
          <CheckboxGroup
            key={cellKey}
            options={column.options?.map((opt) => ({ label: opt, value: opt }))}
            value={Array.isArray(value) ? value : []}
            onChange={(checkedValues) =>
              updateCell(rowIndex, column.name, checkedValues)
            }
            style={{ fontSize: "12px" }}
          />
        );

      case "date":
        return (
          <DatePicker
            key={cellKey}
            value={value ? dayjs(value) : null}
            onChange={(date, dateString) =>
              updateCell(rowIndex, column.name, dateString || "")
            }
            variant="borderless"
            style={{ width: "100%" }}
            size="small"
            placeholder="Select date"
          />
        );

      case "date_range":
        return (
          <RangePicker
            key={cellKey}
            value={
              value && Array.isArray(value) && value.length === 2
                ? [dayjs(value[0]), dayjs(value[1])]
                : null
            }
            onChange={(dates, dateStrings) =>
              updateCell(rowIndex, column.name, dateStrings)
            }
            variant="borderless"
            style={{ width: "100%" }}
            size="small"
            placeholder={["Start date", "End date"]}
          />
        );

      case "time":
        return (
          <TimePicker
            key={cellKey}
            value={value ? dayjs(value, "HH:mm:ss") : null}
            onChange={(time, timeString) =>
              updateCell(rowIndex, column.name, timeString || "")
            }
            variant="borderless"
            style={{ width: "100%" }}
            size="small"
            placeholder="Select time"
          />
        );

      case "time_range":
        return (
          <TimePicker.RangePicker
            key={cellKey}
            value={
              value && Array.isArray(value) && value.length === 2
                ? [dayjs(value[0], "HH:mm:ss"), dayjs(value[1], "HH:mm:ss")]
                : null
            }
            onChange={(times, timeStrings) =>
              updateCell(rowIndex, column.name, timeStrings)
            }
            variant="borderless"
            style={{ width: "100%" }}
            size="small"
            placeholder={["Start time", "End time"]}
          />
        );

      case "switch":
        return (
          <Switch
            key={cellKey}
            checked={value || false}
            onChange={(checked) => updateCell(rowIndex, column.name, checked)}
            size="small"
          />
        );

      case "range":
        return (
          <div key={cellKey} style={{ padding: "4px 0" }}>
            <Slider
              min={column.validation?.min || 0}
              max={column.validation?.max || 100}
              step={column.validation?.step || 1}
              value={value || 0}
              onChange={(val) => updateCell(rowIndex, column.name, val)}
              style={{ margin: "0 8px" }}
            />
            <div
              style={{ textAlign: "center", fontSize: "10px", color: "#666" }}
            >
              {value || 0}
            </div>
          </div>
        );

      case "color":
        return (
          <ColorPicker
            key={cellKey}
            value={value || "#1677ff"}
            onChange={(color) =>
              updateCell(rowIndex, column.name, color.toHexString())
            }
            size="small"
            showText
          />
        );

      case "file":
      case "image": {
        const isMultiple = column.validation?.isMultiple;
        const currentFiles = isMultiple
          ? Array.isArray(value)
            ? value
            : []
          : value;

        return (
          <div key={cellKey} style={{ minWidth: "160px", padding: "4px" }}>
            <Button
              size="small"
              icon={<NxUpload style={{ fontSize: "14px" }} />}
              style={{
                fontSize: "12px",
                height: "32px",
                padding: "0 12px",
                borderRadius: "6px",
                border: "1px dashed #d1d5db",
                backgroundColor: "#fafafa",
                color: "#374151",
                display: "flex",
                alignItems: "center",
                gap: "6px",
              }}
              onClick={() => {
                setCurrentUploadField({
                  rowIndex,
                  columnName: column.name,
                  isMultiple: isMultiple || false,
                  columnType: column.type,
                });
                setOpenUploadSourceModal(true);
              }}
            >
              Upload
            </Button>
            <div
              style={{
                marginTop: "8px",
                maxHeight: "120px",
                overflowY: "auto",
                overflowX: "hidden",
                paddingRight: "4px",
                scrollbarWidth: "thin",
                scrollbarColor: "#cbd5e1 #f1f5f9",
              }}
              className="custom-scrollbar"
            >
              {isMultiple
                ? Array.isArray(currentFiles) &&
                currentFiles.length > 0 && (
                  <div>
                    {currentFiles.map((file, index) => (
                      <FilePreview
                        key={index}
                        file={file}
                        isImage={column.type === "image"}
                        onRemove={() => {
                          const newFiles = currentFiles.filter(
                            (_, i) => i !== index
                          );
                          updateCell(rowIndex, column.name, newFiles);
                        }}
                      />
                    ))}
                  </div>
                )
                : currentFiles && (
                  <FilePreview
                    file={currentFiles}
                    isImage={column.type === "image"}
                    onRemove={() => {
                      updateCell(rowIndex, column.name, null);
                    }}
                  />
                )}
            </div>
          </div>
        );
      }

      case "signature":
        return (
          <div key={cellKey} style={{ minWidth: "200px", minHeight: "100px" }}>
            <SignatureCanvas
              ref={(ref) => {
                if (ref) {
                  signatureRefs.current[cellKey] = ref;
                }
              }}
              canvasProps={{
                style: {
                  border: "1px dashed #ccc",
                  borderRadius: "4px",
                  height: "80px",
                  width: "100%",
                },
              }}
              onEnd={() => {
                if (signatureRefs.current[cellKey]) {
                  const dataUrl = signatureRefs.current[cellKey].toDataURL();
                  updateCell(rowIndex, column.name, dataUrl);
                }
              }}
            />
            <Button
              size="small"
              onClick={() => {
                if (signatureRefs.current[cellKey]) {
                  signatureRefs.current[cellKey].clear();
                  updateCell(rowIndex, column.name, "");
                }
              }}
              style={{ fontSize: "10px", marginTop: "2px" }}
            >
              Clear
            </Button>
          </div>
        );

      case "url":
        return (
          <div key={cellKey} style={{ display: "flex", alignItems: "center", width: "100%", gap: "4px" }}>
            {value ? (
              <a
                href={value}
                target="_blank"
                rel="noopener noreferrer"
                title={value}
                style={{
                  fontSize: "12px",
                  color: "#1677ff",
                  textDecoration: "none",
                  overflow: "hidden",
                  textOverflow: "ellipsis",
                  whiteSpace: "nowrap",
                  padding: "0 8px",
                }}
                onMouseEnter={(e) => (e.target.style.textDecoration = "underline")}
                onMouseLeave={(e) => (e.target.style.textDecoration = "none")}
              >
                View Document
              </a>
            ) : (
              <Input
                value=""
                placeholder={`Enter ${column.label?.toLowerCase()}`}
                variant="borderless"
                style={cellStyle}
                size="small"
                onChange={(e) => updateCell(rowIndex, column.name, e.target.value)}
              />
            )}
          </div>
        );

      case "richtext":
        return (
          <div key={cellKey} style={{ minWidth: "300px", minHeight: "120px" }}>
            <ReactQuill
              value={value || ""}
              onChange={(content) => updateCell(rowIndex, column.name, content)}
              placeholder={column.label}
              style={{ fontSize: "12px" }}
              modules={{
                toolbar: [
                  ["bold", "italic", "underline"],
                  [{ list: "ordered" }, { list: "bullet" }],
                  ["link"],
                  ["clean"],
                ],
              }}
              formats={[
                "bold",
                "italic",
                "underline",
                "list",
                "link",
              ]}
            />
          </div>
        );

      default:
        return (
          <Input
            key={cellKey}
            value={value || ""}
            onChange={(e) => updateCell(rowIndex, column.name, e.target.value)}
            placeholder={`Enter ${column.label?.toLowerCase()}`}
            variant="borderless"
            style={cellStyle}
            size="small"
          />
        );
    }
  };

  return (
    <div
      style={{
        border: "1px solid #d9d9d9",
        borderRadius: "6px",
        overflow: "hidden",
      }}
    >
      {/* Table Container with Horizontal Scroll */}
      <div
        style={{
          overflowX: "auto",
          width: "100%",
        }}
      >
        {/* Table Header */}
        <div
          style={{
            display: "grid",
            gridTemplateColumns: `repeat(${columns.length}, minmax(150px, 1fr)) 60px`,
            backgroundColor: "#fafafa",
            borderBottom: "1px solid #d9d9d9",
            padding: "8px 0",
            minWidth:
              columns.length > 4
                ? `${columns.length * 150 + 60}px`
                : "100%",
          }}
        >
          {columns.map((column) => (
            <div
              key={column.name}
              style={{
                padding: "8px 12px",
                fontWeight: "600",
                borderRight: "1px solid #e8e8e8",
                fontSize: "14px",
                whiteSpace: "nowrap",
                overflow: "hidden",
                textOverflow: "ellipsis",
              }}
            >
              {column.label}
              {column.required && <span style={{ color: "#ff4d4f" }}> *</span>}
            </div>
          ))}
          <div
            style={{
              padding: "8px 12px",
              textAlign: "center",
              fontWeight: "600",
              fontSize: "14px",
            }}
          >
            Action
          </div>
        </div>

        {/* Table Rows */}
        {tableData.length > 0 ? (
          tableData.map((row, rowIndex) => (
            <div
              key={rowIndex}
              style={{
                display: "grid",
                gridTemplateColumns: `repeat(${columns.length}, minmax(150px, 1fr)) 60px`,
                borderBottom:
                  rowIndex < tableData.length - 1
                    ? "1px solid #e8e8e8"
                    : "none",
                transition: "background-color 0.2s",
                minWidth:
                  columns.length > 4
                    ? `${columns.length * 150 + 60}px`
                    : "100%",
              }}
              onMouseEnter={(e) =>
                (e.currentTarget.style.backgroundColor = "#f5f5f5")
              }
              onMouseLeave={(e) =>
                (e.currentTarget.style.backgroundColor = "transparent")
              }
            >
              {columns.map((column) => (
                <div
                  key={`${rowIndex}-${column.name}`}
                  style={{
                    borderRight: "1px solid #e8e8e8",
                    minHeight: "40px",
                    display: "flex",
                    alignItems: "center",
                    flexWrap: "wrap",
                    gap: "2px",
                  }}
                >
                  <div style={{ width: "100%", padding: "2px 4px" }}>
                    {renderCell(column, rowIndex)}
                  </div>
                </div>
              ))}

              <div
                style={{
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  padding: "2px",
                }}
              >
                <Button
                  type="text"
                  size="small"
                  danger
                  icon={<NxTrash />}
                  onClick={() => deleteRow(rowIndex)}
                  style={{
                    border: "none",
                    boxShadow: "none",
                    width: "32px",
                    height: "32px",
                  }}
                  title="Delete row"
                />
              </div>
            </div>
          ))
        ) : (
          <div
            style={{
              padding: "40px 20px",
              textAlign: "center",
              color: "#999",
              backgroundColor: "#fafafa",
              minWidth:
                columns.length > 4
                  ? `${columns.length * 150 + 60}px`
                  : "100%",
            }}
          >
            <div style={{ fontSize: "16px", marginBottom: "8px" }}>
              No data available
            </div>
            <div style={{ fontSize: "14px" }}>
              Click "Add Row" below to start adding data
            </div>
          </div>
        )}
      </div>

      <div
        style={{
          padding: "12px",
          borderTop: "1px solid #e8e8e8",
          backgroundColor: "#fafafa",
        }}
      >
        <Button
          type="dashed"
          size="middle"
          icon={<NxPlus />}
          onClick={addRow}
          block
          style={{
            height: "40px",
            fontSize: "14px",
            fontWeight: "500",
          }}
        >
          Add Row
        </Button>
      </div>

      {tableData.length > 0 && (
        <div
          style={{
            padding: "8px 12px",
            backgroundColor: "#f0f0f0",
            borderTop: "1px solid #e8e8e8",
            fontSize: "12px",
            color: "#666",
            textAlign: "right",
          }}
        >
          Total rows: {tableData.length}
        </div>
      )}

      {/* Upload Source Selection Modal */}
      <Modal
        open={openUploadSourceModal}
        onCancel={() => {
          setOpenUploadSourceModal(false);
          setCurrentUploadField(null);
        }}
        footer={null}
        centered
        width={400}
        title="Choose Upload Source"
        zIndex={5000}
      >
        <div className="space-y-5 p-3">
          <Button
            type="primary"
            size="large"
            icon={<NxFolder />}
            onClick={handleMinIOUpload}
            block
            className="h-10 text-lg"
          >
            <div>
              <div className="font-semibold">Select from Op store</div>
            </div>
          </Button>
          <Button
            type="default"
            size="large"
            icon={<NxUpload />}
            onClick={handleLocalUpload}
            block
            className="h-10 text-lg"
          >
            <div>
              <div className="font-semibold">Upload from Local Machine</div>
            </div>
          </Button>
        </div>
      </Modal>

      {/* DMS/MinIO File Browser Modal */}
      <AttachmentModalWrapper
        open={openMinIOBrowserModal}
        onCancel={() => {
          setOpenMinIOBrowserModal(false);
          setCurrentUploadField(null);
        }}
        onSelectFile={handleMinIOFileSelect}
        isMultiple={currentUploadField?.isMultiple || false}
        currentUploadField={currentUploadField}
      />

      {/* Text Detail Modal - for viewing/editing long text content */}
      <Modal
        open={textModal.open}
        onCancel={() => setTextModal((prev) => ({ ...prev, open: false }))}
        title={
          <div style={{ display: "flex", alignItems: "center", gap: "8px" }}>
            <span style={{ width: "4px", height: "20px", backgroundColor: "#3b82f6", borderRadius: "4px", display: "inline-block" }} />
            <span>{textModal.title || "Details"}</span>
          </div>
        }
        footer={[
          <Button key="cancel" onClick={() => setTextModal((prev) => ({ ...prev, open: false }))}>
            Cancel
          </Button>,
          <Button
            key="save"
            type="primary"
            onClick={() => {
              if (textModal.rowIndex !== null && textModal.columnName) {
                updateCell(textModal.rowIndex, textModal.columnName, textModal.value);
              }
              setTextModal((prev) => ({ ...prev, open: false }));
            }}
          >
            Save
          </Button>,
        ]}
        width="70vw"
        style={{ maxWidth: 900, top: 40 }}
        styles={{ body: { height: "60vh", overflow: "auto" } }}
        zIndex={5000}
      >
        <div style={{ padding: "8px 0", height: "100%" }}>
          <TextArea
            value={textModal.value}
            onChange={(e) => setTextModal((prev) => ({ ...prev, value: e.target.value }))}
            style={{ height: "calc(60vh - 40px)", resize: "none", fontSize: "14px" }}
            placeholder="Enter text..."
          />
        </div>
      </Modal>
    </div>
  );
};

export default TableViewer;
