export const VALIDATION_FIELD_CONFIGS = {
  minLength: { label: "Min Length", type: "number", min: 0, defaultValue: 1 },
  maxLength: { label: "Max Length", type: "number", min: 0, defaultValue: "" },
  pattern: {
    label: "Pattern",
    type: "text",
    placeholder: "Regex",
    defaultValue: "",
  },
  min: { label: "Min", type: "number", defaultValue: 0 },
  max: { label: "Max", type: "number", defaultValue: "" },
  isInteger: { label: "Integer Only", type: "checkbox", defaultValue: false },
  isPositive: { label: "Positive Only", type: "checkbox", defaultValue: true },
  minDate: { label: "Min Date", type: "date", defaultValue: "" },
  maxDate: { label: "Max Date", type: "date", defaultValue: "" },
  startDateBeforeOrEqualEndDate: {
    label: "Start ≤ End Date",
    type: "checkbox",
    defaultValue: true,
  },
  minTime: { label: "Min Time", type: "time", defaultValue: "" },
  maxTime: { label: "Max Time", type: "time", defaultValue: "" },
  startTimeBeforeOrEqualEndTime: {
    label: "Start ≤ End Time",
    type: "checkbox",
    defaultValue: true,
  },
  minSelection: {
    label: "Min Selection",
    type: "number",
    min: 0,
    defaultValue: 1,
  },
  maxSelection: {
    label: "Max Selection",
    type: "number",
    min: 0,
    defaultValue: "",
  },
  isMultiple: {
    label: "Multiple Selection",
    type: "checkbox",
    defaultValue: false,
  },
  fileType: {
    label: "File Types",
    type: "text",
    placeholder: "pdf,doc,txt",
    defaultValue: "pdf,doc,txt",
  },
  maxFileSize: {
    label: "Max File Size (MB)",
    type: "number",
    min: 0,
    defaultValue: 10,
  },
  resolution: {
    label: "Resolution",
    type: "text",
    placeholder: "1920x1080",
    defaultValue: "1920x1080",
  },
  aspectRatio: {
    label: "Aspect Ratio",
    type: "text",
    placeholder: "16:9",
    defaultValue: "16:9",
  },
  containsSpecialChar: {
    label: "Special Characters",
    type: "checkbox",
    defaultValue: true,
  },
  strengthCheck: {
    label: "Strength Check",
    type: "checkbox",
    defaultValue: true,
  },
  step: { label: "Step", type: "number", min: 0, defaultValue: 1 },
  maxSize: {
    label: "Max Size (KB)",
    type: "number",
    min: 0,
    defaultValue: 100,
  },
  maxDimensions: {
    label: "Max Dimensions",
    type: "text",
    placeholder: "500x300",
    defaultValue: "500x300",
  },
  minContentLength: {
    label: "Min Content Length",
    type: "number",
    min: 0,
    defaultValue: 10,
  },
  maxContentLength: {
    label: "Max Content Length",
    type: "number",
    min: 0,
    defaultValue: 99999,
  },
  disallowedTags: {
    label: "Disallowed Tags",
    type: "text",
    placeholder: "script,iframe",
    defaultValue: "script,iframe",
  },
  errorMessage: {
    label: "Error Message",
    type: "text",
    placeholder: "Error Message",
    defaultValue: "",
  },
  apiDependencyEnabled: {
    label: "API Dependency",
    type: "checkbox",
    defaultValue: false,
  },
  apiDependencyField: {
    label: "Depends On Field",
    type: "select",
    defaultValue: "",
  },
};
