/**
 * Canonical RBAC permission catalog — the single source of truth for every
 * permission key the API enforces via `requirePermission(...)`.
 *
 * Lives in `src/` (not `prisma/seed.ts`) so it's compiled into the production
 * image and can be synced to the DB at API startup (see rbac-sync.ts). The
 * seed imports this same list so dev seeding and prod stay in lockstep.
 */
export interface PermissionDef {
  key: string;
  module: string;
  action: string;
  description: string;
}

export const PERMISSIONS: PermissionDef[] = [
  // ── Admin ────────────────────────────────────────────
  { key: 'user.create',       module: 'USER',       action: 'CREATE', description: 'Create users' },
  { key: 'user.read',         module: 'USER',       action: 'READ',   description: 'View users' },
  { key: 'user.update',       module: 'USER',       action: 'UPDATE', description: 'Edit users' },
  { key: 'user.delete',       module: 'USER',       action: 'DELETE', description: 'Deactivate users' },
  { key: 'role.create',       module: 'ROLE',       action: 'CREATE', description: 'Create roles' },
  { key: 'role.read',         module: 'ROLE',       action: 'READ',   description: 'View roles' },
  { key: 'role.update',       module: 'ROLE',       action: 'UPDATE', description: 'Edit roles' },
  { key: 'role.delete',       module: 'ROLE',       action: 'DELETE', description: 'Delete roles' },
  { key: 'department.create', module: 'DEPARTMENT', action: 'CREATE', description: 'Create departments' },
  { key: 'department.read',   module: 'DEPARTMENT', action: 'READ',   description: 'View departments' },
  { key: 'department.update', module: 'DEPARTMENT', action: 'UPDATE', description: 'Edit departments' },
  { key: 'department.delete', module: 'DEPARTMENT', action: 'DELETE', description: 'Delete departments' },
  { key: 'org.read',          module: 'ORG',        action: 'READ',   description: 'View organization settings' },
  { key: 'org.update',        module: 'ORG',        action: 'UPDATE', description: 'Edit organization settings' },
  // Site / Facility master data (Configuration → Facilities). CRUD gates the
  // admin management surface; the list stays readable via `org.read` too so
  // operational pickers (ticket site selector, LMS targeting) keep working.
  { key: 'site.read',         module: 'SITE',       action: 'READ',   description: 'View facilities / sites' },
  { key: 'site.create',       module: 'SITE',       action: 'CREATE', description: 'Create facilities / sites' },
  { key: 'site.update',       module: 'SITE',       action: 'UPDATE', description: 'Edit facilities / sites' },
  { key: 'site.delete',       module: 'SITE',       action: 'DELETE', description: 'Delete facilities / sites' },
  // Site scoping — holders bypass per-site ticket scoping and may view/switch
  // across every site. Non-holders are pinned to their own assigned site.
  { key: 'site.view_all',     module: 'SITE',       action: 'MANAGE', description: 'View data across all sites (bypass per-site scoping)' },
  // ── Dashboard ────────────────────────────────────────
  { key: 'dashboard.read',    module: 'DASHBOARD',  action: 'READ',   description: 'View the dashboard (KPIs & workload overview)' },
  // ── QMS modules ──────────────────────────────────────
  { key: 'doc.read',          module: 'DOC',        action: 'READ',    description: 'View documents' },
  { key: 'doc.write',         module: 'DOC',        action: 'WRITE',   description: 'Create/edit documents' },
  { key: 'doc.approve',       module: 'DOC',        action: 'APPROVE', description: 'Approve documents' },
  { key: 'capa.read',         module: 'CAPA',       action: 'READ',    description: 'View CAPAs' },
  { key: 'capa.write',        module: 'CAPA',       action: 'WRITE',   description: 'Create/edit CAPAs' },
  { key: 'capa.approve',      module: 'CAPA',       action: 'APPROVE', description: 'Approve CAPAs' },
  { key: 'nc.read',           module: 'NC',         action: 'READ',    description: 'View Non-Conformances' },
  { key: 'nc.write',          module: 'NC',         action: 'WRITE',   description: 'Create/edit NCs' },
  { key: 'nc.approve',        module: 'NC',         action: 'APPROVE', description: 'Approve NC closures' },
  { key: 'audit.read',        module: 'AUDIT',      action: 'READ',    description: 'View audits' },
  { key: 'audit.write',       module: 'AUDIT',      action: 'WRITE',   description: 'Create/conduct audits' },
  { key: 'audit.approve',     module: 'AUDIT',      action: 'APPROVE', description: 'Sign-off audit reports' },
  { key: 'fmea.read',         module: 'FMEA',       action: 'READ',    description: 'View FMEAs' },
  { key: 'fmea.write',        module: 'FMEA',       action: 'WRITE',   description: 'Create/edit FMEAs' },
  { key: 'risk.read',         module: 'RISK',       action: 'READ',    description: 'View risks' },
  { key: 'risk.write',        module: 'RISK',       action: 'WRITE',   description: 'Create/edit risks (legacy coarse grant)' },
  { key: 'risk.create',       module: 'RISK',       action: 'CREATE',  description: 'Create risks' },
  { key: 'risk.update',       module: 'RISK',       action: 'UPDATE',  description: 'Edit risks' },
  { key: 'risk.delete',       module: 'RISK',       action: 'DELETE',  description: 'Delete risks' },
  { key: 'risk.accept',       module: 'RISK',       action: 'APPROVE', description: 'Accept residual risk' },
  { key: 'risk_register.read',      module: 'RISK_REGISTER',   action: 'READ',    description: 'View risk registers' },
  { key: 'risk_register.create',    module: 'RISK_REGISTER',   action: 'CREATE',  description: 'Create risk registers' },
  { key: 'risk_register.update',    module: 'RISK_REGISTER',   action: 'UPDATE',  description: 'Edit risk registers' },
  { key: 'risk_register.delete',    module: 'RISK_REGISTER',   action: 'DELETE',  description: 'Delete risk registers' },
  { key: 'risk_assessment.read',    module: 'RISK_ASSESSMENT', action: 'READ',    description: 'View risk assessments' },
  { key: 'risk_assessment.create',  module: 'RISK_ASSESSMENT', action: 'CREATE',  description: 'Create risk assessments' },
  { key: 'risk_assessment.update',  module: 'RISK_ASSESSMENT', action: 'UPDATE',  description: 'Edit risk assessments' },
  { key: 'risk_assessment.delete',  module: 'RISK_ASSESSMENT', action: 'DELETE',  description: 'Delete risk assessments' },
  { key: 'risk_assessment.approve', module: 'RISK_ASSESSMENT', action: 'APPROVE', description: 'Approve/reject risk assessments' },
  { key: 'risk_control.read',       module: 'RISK_CONTROL',    action: 'READ',    description: 'View risk controls' },
  { key: 'risk_control.create',     module: 'RISK_CONTROL',    action: 'CREATE',  description: 'Create risk controls' },
  { key: 'risk_control.update',     module: 'RISK_CONTROL',    action: 'UPDATE',  description: 'Edit risk controls' },
  { key: 'risk_control.delete',     module: 'RISK_CONTROL',    action: 'DELETE',  description: 'Delete risk controls' },
  { key: 'risk_control.approve',    module: 'RISK_CONTROL',    action: 'APPROVE', description: 'Verify risk control effectiveness' },
  { key: 'risk_review.read',        module: 'RISK_REVIEW',     action: 'READ',    description: 'View risk reviews' },
  { key: 'risk_review.create',      module: 'RISK_REVIEW',     action: 'CREATE',  description: 'Schedule risk reviews' },
  { key: 'risk_review.update',      module: 'RISK_REVIEW',     action: 'UPDATE',  description: 'Complete risk reviews' },
  { key: 'risk_framework.read',     module: 'RISK_FRAMEWORK',  action: 'READ',    description: 'View risk frameworks' },
  { key: 'risk_framework.create',   module: 'RISK_FRAMEWORK',  action: 'CREATE',  description: 'Create risk frameworks' },
  { key: 'risk_framework.update',   module: 'RISK_FRAMEWORK',  action: 'UPDATE',  description: 'Edit risk frameworks' },
  { key: 'risk_framework.delete',   module: 'RISK_FRAMEWORK',  action: 'DELETE',  description: 'Delete risk frameworks' },
  { key: 'risk_category.read',      module: 'RISK_CATEGORY',   action: 'READ',    description: 'View risk categories' },
  { key: 'risk_category.create',    module: 'RISK_CATEGORY',   action: 'CREATE',  description: 'Create risk categories' },
  { key: 'risk_category.update',    module: 'RISK_CATEGORY',   action: 'UPDATE',  description: 'Edit risk categories' },
  { key: 'risk_category.delete',    module: 'RISK_CATEGORY',   action: 'DELETE',  description: 'Delete risk categories' },
  // Cross-module read model: gates the risk chip other modules render on their
  // own records (supplier, equipment, document, …). Separable from risk.read so
  // a supplier-page viewer can see "this supplier is HIGH risk" without being
  // granted the risk register itself.
  { key: 'risk_profile.read',       module: 'RISK_PROFILE',    action: 'READ',    description: 'View the risk profile of any linked record' },
  { key: 'risk_trigger.read',       module: 'RISK_TRIGGER',    action: 'READ',    description: 'View risk trigger rules' },
  { key: 'risk_trigger.create',     module: 'RISK_TRIGGER',    action: 'CREATE',  description: 'Create risk trigger rules' },
  { key: 'risk_trigger.update',     module: 'RISK_TRIGGER',    action: 'UPDATE',  description: 'Edit risk trigger rules' },
  { key: 'risk_trigger.delete',     module: 'RISK_TRIGGER',    action: 'DELETE',  description: 'Delete risk trigger rules' },
  { key: 'risk_appetite.read',      module: 'RISK_APPETITE',   action: 'READ',    description: 'View organisational risk appetite' },
  { key: 'risk_appetite.create',    module: 'RISK_APPETITE',   action: 'CREATE',  description: 'Define risk appetite' },
  { key: 'risk_appetite.update',    module: 'RISK_APPETITE',   action: 'UPDATE',  description: 'Edit risk appetite' },
  { key: 'risk_appetite.delete',    module: 'RISK_APPETITE',   action: 'DELETE',  description: 'Delete risk appetite' },
  { key: 'risk.override_gate',      module: 'RISK',            action: 'APPROVE', description: 'Override a risk-driven block (change approval, CoA issue, batch release) with an e-signature' },
  { key: 'risk_link.read',          module: 'RISK_LINK',       action: 'READ',    description: 'View risk links / reverse lookups' },
  { key: 'risk_library.read',       module: 'RISK_LIBRARY',    action: 'READ',    description: 'View hazard/control libraries' },
  { key: 'risk_library.create',     module: 'RISK_LIBRARY',    action: 'CREATE',  description: 'Create library items' },
  { key: 'risk_library.update',     module: 'RISK_LIBRARY',    action: 'UPDATE',  description: 'Edit library items' },
  { key: 'risk_library.delete',     module: 'RISK_LIBRARY',    action: 'DELETE',  description: 'Delete library items' },
  { key: 'supplier.read',     module: 'SUPPLIER',   action: 'READ',    description: 'View suppliers' },
  { key: 'supplier.write',    module: 'SUPPLIER',   action: 'WRITE',   description: 'Create/edit suppliers' },
  { key: 'training.read',     module: 'TRAINING',   action: 'READ',    description: 'View training' },
  { key: 'training.write',    module: 'TRAINING',   action: 'WRITE',   description: 'Manage training' },
  { key: 'inspection.read',   module: 'INSPECTION', action: 'READ',    description: 'View inspections' },
  { key: 'inspection.write',  module: 'INSPECTION', action: 'WRITE',   description: 'Record inspections' },
  { key: 'calibration.read',  module: 'CALIBRATION',action: 'READ',    description: 'View calibration records' },
  { key: 'calibration.write', module: 'CALIBRATION',action: 'WRITE',   description: 'Record calibrations' },
  // ── Workflow ─────────────────────────────────────────
  { key: 'workflow.read',           module: 'WORKFLOW', action: 'READ',   description: 'View workflows' },
  { key: 'workflow.create',         module: 'WORKFLOW', action: 'CREATE', description: 'Create workflow shells' },
  { key: 'workflow.update',         module: 'WORKFLOW', action: 'UPDATE', description: 'Edit/version workflows' },
  { key: 'workflow.delete',         module: 'WORKFLOW', action: 'DELETE', description: 'Soft-delete workflows' },
  { key: 'workflow.lookups.read',   module: 'WORKFLOW', action: 'READ',   description: 'View workflow lookup tables' },
  { key: 'workflow.lookups.manage', module: 'WORKFLOW', action: 'MANAGE', description: 'Manage workflow lookup tables (types, statuses, criteria)' },
  // ── Ticket ───────────────────────────────────────────
  // The global `ticket.*` "All Workflow Types" master was retired — ticket
  // access is granted exclusively via the per-type `wf_type.<id>.*` keys (see
  // lib/rbac-workflow-types.ts + docs/per-module-ticket-master-plan.md).
  // ── Dynamic Forms ────────────────────────────────────
  { key: 'form.read',             module: 'FORM',            action: 'READ',   description: 'View form templates' },
  { key: 'form.create',           module: 'FORM',            action: 'CREATE', description: 'Create form templates' },
  { key: 'form.update',           module: 'FORM',            action: 'UPDATE', description: 'Edit/save form templates' },
  { key: 'form.delete',           module: 'FORM',            action: 'DELETE', description: 'Delete form templates' },
  { key: 'form_type.create',      module: 'FORM_TYPE',       action: 'CREATE', description: 'Create form/checklist types' },
  { key: 'form_type.update',      module: 'FORM_TYPE',       action: 'UPDATE', description: 'Edit form/checklist types' },
  { key: 'form_type.delete',      module: 'FORM_TYPE',       action: 'DELETE', description: 'Delete form/checklist types' },
  { key: 'field_type.create',     module: 'FIELD_TYPE',      action: 'CREATE', description: 'Create custom field types' },
  { key: 'field_type.update',     module: 'FIELD_TYPE',      action: 'UPDATE', description: 'Edit custom field types' },
  { key: 'field_type.delete',     module: 'FIELD_TYPE',      action: 'DELETE', description: 'Delete custom field types' },
  { key: 'form_submission.read',  module: 'FORM_SUBMISSION', action: 'READ',   description: 'View form submissions' },
  { key: 'form_submission.create',module: 'FORM_SUBMISSION', action: 'CREATE', description: 'Submit form responses' },
  { key: 'form_submission.update',module: 'FORM_SUBMISSION', action: 'UPDATE', description: 'Update submission status (approve/reject)' },
  { key: 'form_submission.delete',module: 'FORM_SUBMISSION', action: 'DELETE', description: 'Delete form submissions' },
  // ── DMS — Controlled documents ───────────────────────
  { key: 'document.read',   module: 'DMS', action: 'READ',   description: 'View controlled documents' },
  { key: 'document.create', module: 'DMS', action: 'CREATE', description: 'Create controlled documents' },
  { key: 'document.update', module: 'DMS', action: 'UPDATE', description: 'Edit document content / draft revisions' },
  { key: 'document.issue',  module: 'DMS', action: 'ISSUE',  description: 'Make a document effective / retire it' },
  { key: 'document.approve',module: 'DMS', action: 'APPROVE',description: 'Approve documents for issue (Phase 2)' },
  { key: 'document.delete', module: 'DMS', action: 'DELETE', description: 'Delete DRAFT documents' },
  // ── LIMS — Lab Registry ──────────────────────────────
  { key: 'lab.read',   module: 'LIMS', action: 'READ',   description: 'View laboratories' },
  { key: 'lab.create', module: 'LIMS', action: 'CREATE', description: 'Register laboratories' },
  { key: 'lab.update', module: 'LIMS', action: 'UPDATE', description: 'Edit laboratories' },
  { key: 'lab.delete', module: 'LIMS', action: 'DELETE', description: 'Remove laboratories' },
  { key: 'equipment.read',   module: 'LIMS', action: 'READ',   description: 'View equipment & calibration' },
  { key: 'equipment.create', module: 'LIMS', action: 'CREATE', description: 'Register equipment' },
  { key: 'equipment.update', module: 'LIMS', action: 'UPDATE', description: 'Edit equipment / record calibration' },
  { key: 'equipment.delete', module: 'LIMS', action: 'DELETE', description: 'Remove equipment' },
  { key: 'certification.read',   module: 'LIMS', action: 'READ',   description: 'View certifications' },
  { key: 'certification.create', module: 'LIMS', action: 'CREATE', description: 'Add certifications' },
  { key: 'certification.update', module: 'LIMS', action: 'UPDATE', description: 'Edit / renew certifications' },
  { key: 'certification.delete', module: 'LIMS', action: 'DELETE', description: 'Remove certifications' },
  { key: 'method.read',   module: 'LIMS', action: 'READ',   description: 'View test methods' },
  { key: 'method.create', module: 'LIMS', action: 'CREATE', description: 'Create test methods' },
  { key: 'method.update', module: 'LIMS', action: 'UPDATE', description: 'Edit test methods' },
  { key: 'method.delete', module: 'LIMS', action: 'DELETE', description: 'Remove test methods' },
  { key: 'specification.read',    module: 'LIMS', action: 'READ',    description: 'View specifications' },
  { key: 'specification.create',  module: 'LIMS', action: 'CREATE',  description: 'Create specifications' },
  { key: 'specification.update',  module: 'LIMS', action: 'UPDATE',  description: 'Edit draft specifications' },
  { key: 'specification.approve', module: 'LIMS', action: 'APPROVE', description: 'Approve / retire specifications' },
  { key: 'specification.delete',  module: 'LIMS', action: 'DELETE',  description: 'Delete draft specifications' },
  { key: 'storage.read',   module: 'LIMS', action: 'READ',   description: 'View storage locations' },
  { key: 'storage.create', module: 'LIMS', action: 'CREATE', description: 'Add storage locations' },
  { key: 'storage.update', module: 'LIMS', action: 'UPDATE', description: 'Edit storage locations' },
  { key: 'storage.delete', module: 'LIMS', action: 'DELETE', description: 'Remove storage locations' },
  { key: 'sample.read',   module: 'LIMS', action: 'READ',   description: 'View samples & chain of custody' },
  { key: 'sample.create', module: 'LIMS', action: 'CREATE', description: 'Register samples' },
  { key: 'sample.update', module: 'LIMS', action: 'UPDATE', description: 'Edit samples / custody / aliquots / status' },
  // ── LIMS 2.0 — L0 master data ──
  { key: 'product.read',   module: 'LIMS', action: 'READ',   description: 'View products / materials' },
  { key: 'product.create', module: 'LIMS', action: 'CREATE', description: 'Add products / materials' },
  { key: 'product.update', module: 'LIMS', action: 'UPDATE', description: 'Edit products / materials' },
  { key: 'product.delete', module: 'LIMS', action: 'DELETE', description: 'Remove products / materials' },
  { key: 'analyte.read',   module: 'LIMS', action: 'READ',   description: 'View analytes / components' },
  { key: 'analyte.create', module: 'LIMS', action: 'CREATE', description: 'Add analytes / components' },
  { key: 'analyte.update', module: 'LIMS', action: 'UPDATE', description: 'Edit analytes / components' },
  { key: 'analyte.delete', module: 'LIMS', action: 'DELETE', description: 'Remove analytes / components' },
  { key: 'unit.read',   module: 'LIMS', action: 'READ',   description: 'View units of measure' },
  { key: 'unit.create', module: 'LIMS', action: 'CREATE', description: 'Add units of measure' },
  { key: 'unit.update', module: 'LIMS', action: 'UPDATE', description: 'Edit units of measure' },
  { key: 'unit.delete', module: 'LIMS', action: 'DELETE', description: 'Remove units of measure' },
  { key: 'sampling_point.read',   module: 'LIMS', action: 'READ',   description: 'View sampling points' },
  { key: 'sampling_point.create', module: 'LIMS', action: 'CREATE', description: 'Add sampling points' },
  { key: 'sampling_point.update', module: 'LIMS', action: 'UPDATE', description: 'Edit sampling points' },
  { key: 'sampling_point.delete', module: 'LIMS', action: 'DELETE', description: 'Remove sampling points' },
  { key: 'customer.read',   module: 'LIMS', action: 'READ',   description: 'View customers' },
  { key: 'customer.create', module: 'LIMS', action: 'CREATE', description: 'Add customers' },
  { key: 'customer.update', module: 'LIMS', action: 'UPDATE', description: 'Edit customers' },
  { key: 'customer.delete', module: 'LIMS', action: 'DELETE', description: 'Remove customers' },
  { key: 'supplier.read',   module: 'LIMS', action: 'READ',   description: 'View suppliers' },
  { key: 'supplier.create', module: 'LIMS', action: 'CREATE', description: 'Add suppliers' },
  { key: 'supplier.update', module: 'LIMS', action: 'UPDATE', description: 'Edit suppliers' },
  { key: 'supplier.delete', module: 'LIMS', action: 'DELETE', description: 'Remove suppliers' },
  // ── LIMS 2.0 — L1 test definitions, panels, spec versions ──
  { key: 'test_definition.read',    module: 'LIMS', action: 'READ',    description: 'View test definitions' },
  { key: 'test_definition.create',  module: 'LIMS', action: 'CREATE',  description: 'Create test definitions' },
  { key: 'test_definition.update',  module: 'LIMS', action: 'UPDATE',  description: 'Edit test definitions' },
  { key: 'test_definition.approve', module: 'LIMS', action: 'APPROVE', description: 'Approve test definitions' },
  { key: 'test_definition.delete',  module: 'LIMS', action: 'DELETE',  description: 'Remove test definitions' },
  { key: 'test_panel.read',   module: 'LIMS', action: 'READ',   description: 'View test panels' },
  { key: 'test_panel.create', module: 'LIMS', action: 'CREATE', description: 'Create test panels' },
  { key: 'test_panel.update', module: 'LIMS', action: 'UPDATE', description: 'Edit test panels' },
  { key: 'test_panel.delete', module: 'LIMS', action: 'DELETE', description: 'Remove test panels' },
  { key: 'spec_version.read',    module: 'LIMS', action: 'READ',    description: 'View specification versions' },
  { key: 'spec_version.create',  module: 'LIMS', action: 'CREATE',  description: 'Create specification versions' },
  { key: 'spec_version.update',  module: 'LIMS', action: 'UPDATE',  description: 'Edit / revise specification versions' },
  { key: 'spec_version.approve', module: 'LIMS', action: 'APPROVE', description: 'Approve specification versions' },
  { key: 'spec_version.delete',  module: 'LIMS', action: 'DELETE',  description: 'Remove specification versions' },
  // ── LIMS 2.0 — M-LIMS-B core testing (L2–L5) ──
  { key: 'worklist.read',   module: 'LIMS', action: 'READ',   description: 'View worklists / batches' },
  { key: 'worklist.create', module: 'LIMS', action: 'CREATE', description: 'Create worklists' },
  { key: 'worklist.update', module: 'LIMS', action: 'UPDATE', description: 'Edit / close worklists' },
  { key: 'result.read',   module: 'LIMS', action: 'READ',   description: 'View sample tests & results' },
  { key: 'result.enter',  module: 'LIMS', action: 'CREATE', description: 'Assign tests & enter results' },
  { key: 'result.review', module: 'LIMS', action: 'APPROVE', description: 'Second-person review of results (e-sign)' },
  { key: 'sample.dispose', module: 'LIMS', action: 'APPROVE', description: 'Release / reject samples (e-sign)' },
  { key: 'oos.read',   module: 'LIMS', action: 'READ',   description: 'View OOS/OOT investigations' },
  { key: 'oos.create', module: 'LIMS', action: 'CREATE', description: 'Open OOS investigations' },
  { key: 'oos.update', module: 'LIMS', action: 'UPDATE', description: 'Progress OOS investigations' },
  { key: 'oos.close',  module: 'LIMS', action: 'APPROVE', description: 'Close OOS investigations (e-sign)' },
  // ── LIMS 2.0 — M-LIMS-C  QC + Stability (L6–L7) ──
  { key: 'qc.read',   module: 'LIMS', action: 'READ',   description: 'View QC materials & control charts' },
  { key: 'qc.create', module: 'LIMS', action: 'CREATE', description: 'Add QC control materials' },
  { key: 'qc.update', module: 'LIMS', action: 'UPDATE', description: 'Edit QC materials' },
  { key: 'qc.result', module: 'LIMS', action: 'CREATE', description: 'Record QC results (Levey-Jennings)' },
  { key: 'stability.read',    module: 'LIMS', action: 'READ',    description: 'View stability studies' },
  { key: 'stability.create',  module: 'LIMS', action: 'CREATE',  description: 'Create stability studies' },
  { key: 'stability.update',  module: 'LIMS', action: 'UPDATE',  description: 'Edit / activate / complete stability studies' },
  { key: 'stability.execute', module: 'LIMS', action: 'CREATE',  description: 'Pull stability timepoints' },
  // ── LIMS 2.0 — M-LIMS-D  CoA + analytics (L8, L11, L12) ──
  { key: 'coa.read',   module: 'LIMS', action: 'READ',   description: 'View certificates of analysis' },
  { key: 'coa.create', module: 'LIMS', action: 'CREATE', description: 'Generate certificates of analysis' },
  { key: 'coa.issue',  module: 'LIMS', action: 'APPROVE', description: 'Issue / revoke certificates (e-sign)' },
  { key: 'coa.manage', module: 'LIMS', action: 'UPDATE', description: 'Manage CoA templates' },
  { key: 'lims_dashboard.read', module: 'LIMS', action: 'READ', description: 'View LIMS dashboard, TAT & workload' },
  { key: 'data_review.read',    module: 'LIMS', action: 'READ', description: 'Review audit trail / data integrity' },
  // ── Phase 3.5 — Stage form bindings ──────────────────
  { key: 'stage-form.read',       module: 'STAGE_FORM',      action: 'READ',   description: 'View stage form bindings' },
  { key: 'stage-form.create',     module: 'STAGE_FORM',      action: 'CREATE', description: 'Attach a form to a stage' },
  { key: 'stage-form.update',     module: 'STAGE_FORM',      action: 'UPDATE', description: 'Update a stage form binding (required/position)' },
  { key: 'stage-form.delete',     module: 'STAGE_FORM',      action: 'DELETE', description: 'Detach a form from a stage' },
  // ── Audit (ISO standards & schedules) ────────────────
  { key: 'iso_standard.read',     module: 'ISO_STANDARD',    action: 'READ',   description: 'View ISO standards / audit checklists' },
  { key: 'iso_standard.create',   module: 'ISO_STANDARD',    action: 'CREATE', description: 'Create ISO standards' },
  { key: 'iso_standard.update',   module: 'ISO_STANDARD',    action: 'UPDATE', description: 'Edit ISO standards' },
  { key: 'iso_standard.delete',   module: 'ISO_STANDARD',    action: 'DELETE', description: 'Delete ISO standards' },
  { key: 'audit_schedule.read',   module: 'AUDIT_SCHEDULE',  action: 'READ',   description: 'View audit schedules' },
  { key: 'audit_schedule.create', module: 'AUDIT_SCHEDULE',  action: 'CREATE', description: 'Create audit schedules' },
  { key: 'audit_schedule.update', module: 'AUDIT_SCHEDULE',  action: 'UPDATE', description: 'Edit audit schedules' },
  { key: 'audit_schedule.delete', module: 'AUDIT_SCHEDULE',  action: 'DELETE', description: 'Delete audit schedules' },
  // ── Audit Master (configuration) ─────────────────────
  { key: 'audit_master.read',     module: 'AUDIT_MASTER',    action: 'READ',   description: 'View audit master configurations' },
  { key: 'audit_master.create',   module: 'AUDIT_MASTER',    action: 'CREATE', description: 'Create audit master configurations' },
  { key: 'audit_master.update',   module: 'AUDIT_MASTER',    action: 'UPDATE', description: 'Edit audit master configurations' },
  { key: 'audit_master.delete',   module: 'AUDIT_MASTER',    action: 'DELETE', description: 'Delete audit master configurations' },
  // ── Focus Area (audit master lookup) ─────────────────
  { key: 'focus_area.read',       module: 'FOCUS_AREA',      action: 'READ',   description: 'View audit focus areas' },
  { key: 'focus_area.create',     module: 'FOCUS_AREA',      action: 'CREATE', description: 'Create audit focus areas' },
  { key: 'focus_area.update',     module: 'FOCUS_AREA',      action: 'UPDATE', description: 'Edit audit focus areas' },
  { key: 'focus_area.delete',     module: 'FOCUS_AREA',      action: 'DELETE', description: 'Delete audit focus areas' },
  // ── Audit Type (audit master lookup) ─────────────────
  { key: 'audit_type.read',       module: 'AUDIT_TYPE',      action: 'READ',   description: 'View audit types' },
  { key: 'audit_type.create',     module: 'AUDIT_TYPE',      action: 'CREATE', description: 'Create audit types' },
  { key: 'audit_type.update',     module: 'AUDIT_TYPE',      action: 'UPDATE', description: 'Edit audit types' },
  { key: 'audit_type.delete',     module: 'AUDIT_TYPE',      action: 'DELETE', description: 'Delete audit types' },
  // ── Audit Trail (system-wide change history) ─────────
  // Distinct from `audit_register.*`, which is the internal-audit *module*.
  // Reading the trail is its own privilege: it exposes who did what across
  // every module, including security events.
  { key: 'audit_trail.read',   module: 'AUDIT_TRAIL', action: 'READ',   description: 'View the system audit trail' },
  { key: 'audit_trail.export', module: 'AUDIT_TRAIL', action: 'EXPORT', description: 'Export the audit trail' },
  // ── Audit Register (planning + approval) ─────────────
  { key: 'audit_register.read',    module: 'AUDIT_REGISTER', action: 'READ',    description: 'View audit registers' },
  { key: 'audit_register.create',  module: 'AUDIT_REGISTER', action: 'CREATE',  description: 'Create audit registers' },
  { key: 'audit_register.update',  module: 'AUDIT_REGISTER', action: 'UPDATE',  description: 'Edit / submit audit registers' },
  { key: 'audit_register.approve', module: 'AUDIT_REGISTER', action: 'APPROVE', description: 'Approve or reject audit registers' },
  { key: 'audit_register.delete',  module: 'AUDIT_REGISTER', action: 'DELETE',  description: 'Delete audit registers' },
  // ── Audit Program (execution) ────────────────────────
  { key: 'audit_program.read',    module: 'AUDIT_PROGRAM', action: 'READ',    description: 'View audit programs' },
  { key: 'audit_program.execute', module: 'AUDIT_PROGRAM', action: 'EXECUTE', description: 'Start / complete an audit program' },
  // ── Audit Findings ───────────────────────────────────
  { key: 'audit_finding.read',   module: 'AUDIT_FINDING', action: 'READ',   description: 'View audit findings' },
  { key: 'audit_finding.create', module: 'AUDIT_FINDING', action: 'CREATE', description: 'Record audit findings' },
  { key: 'audit_finding.update', module: 'AUDIT_FINDING', action: 'UPDATE', description: 'Edit audit findings' },
  { key: 'audit_finding.delete', module: 'AUDIT_FINDING', action: 'DELETE', description: 'Delete audit findings' },
  // ── Non-Conformance / CAPA bridge ────────────────────
  { key: 'non_conformance.read',   module: 'NON_CONFORMANCE', action: 'READ',   description: 'View non-conformances (CAPA tracking)' },
  { key: 'non_conformance.create', module: 'NON_CONFORMANCE', action: 'CREATE', description: 'Promote a finding to a non-conformance' },
  { key: 'non_conformance.update', module: 'NON_CONFORMANCE', action: 'UPDATE', description: 'Update NC status / link CAPA ticket' },
  // ── CAPA (corrective & preventive action) ────────────
  { key: 'capa.create', module: 'CAPA', action: 'CREATE', description: 'Raise a CAPA from a non-conformance' },
  { key: 'capa.update', module: 'CAPA', action: 'UPDATE', description: 'Edit / progress / verify CAPAs' },
  { key: 'capa.delete', module: 'CAPA', action: 'DELETE', description: 'Delete CAPAs' },
  // ── Generic Findings (non-audit modules) ─────────────
  // Access is per-workflow-type, not a single global key: `finding.<typeId>.*`
  // (module FINDING_TYPE), synced dynamically for every type with
  // supportsFindings=true. See lib/rbac-findings.ts. No static keys here.
  // ── Action Items ─────────────────────────────────────
  { key: 'action_item.read',   module: 'ACTION_ITEM', action: 'READ',   description: 'View action items' },
  { key: 'action_item.create', module: 'ACTION_ITEM', action: 'CREATE', description: 'Create action items' },
  { key: 'action_item.update', module: 'ACTION_ITEM', action: 'UPDATE', description: 'Edit / progress action items' },
  { key: 'action_item.delete', module: 'ACTION_ITEM', action: 'DELETE', description: 'Delete action items' },
  // ── Phase 3 — Approvals ─────────────────────────────
  { key: 'approval.read',          module: 'APPROVAL', action: 'READ',    description: 'View approval instances on tickets' },
  { key: 'approval.decide',        module: 'APPROVAL', action: 'DECIDE',  description: 'Approve or reject a pending approval instance' },
  { key: 'approval.policy.read',   module: 'APPROVAL', action: 'READ',    description: 'View approval policies on workflows' },
  { key: 'approval.policy.create', module: 'APPROVAL', action: 'CREATE',  description: 'Create approval policies' },
  { key: 'approval.policy.update', module: 'APPROVAL', action: 'UPDATE',  description: 'Edit approval policies' },
  { key: 'approval.policy.delete', module: 'APPROVAL', action: 'DELETE',  description: 'Delete approval policies' },
  // ── Phase 3 — SLA ────────────────────────────────────
  { key: 'sla.policy.read',         module: 'SLA', action: 'READ',    description: 'View SLA policies' },
  { key: 'sla.policy.create',       module: 'SLA', action: 'CREATE',  description: 'Create SLA policies' },
  { key: 'sla.policy.update',       module: 'SLA', action: 'UPDATE',  description: 'Edit SLA policies' },
  { key: 'sla.policy.delete',       module: 'SLA', action: 'DELETE',  description: 'Delete SLA policies' },
  { key: 'sla.timer.read',          module: 'SLA', action: 'READ',    description: 'View SLA timers and events' },
  { key: 'sla.timer.extend',        module: 'SLA', action: 'UPDATE',  description: 'Request SLA timer extensions' },
  { key: 'sla.timer.extend.approve',module: 'SLA', action: 'APPROVE', description: 'Approve or reject SLA extension requests' },
  // ── Escalation matrix ────────────────────────────────
  { key: 'escalation.read',   module: 'ESCALATION', action: 'READ',   description: 'View escalation rules' },
  { key: 'escalation.create', module: 'ESCALATION', action: 'CREATE', description: 'Create escalation rules' },
  { key: 'escalation.update', module: 'ESCALATION', action: 'UPDATE', description: 'Edit escalation rules' },
  { key: 'escalation.delete', module: 'ESCALATION', action: 'DELETE', description: 'Delete escalation rules' },
  // ── Phase 3 — Business calendars ─────────────────────
  { key: 'business-calendar.read',   module: 'BUSINESS_CALENDAR', action: 'READ',   description: 'View business calendars' },
  { key: 'business-calendar.create', module: 'BUSINESS_CALENDAR', action: 'CREATE', description: 'Create business calendars' },
  { key: 'business-calendar.update', module: 'BUSINESS_CALENDAR', action: 'UPDATE', description: 'Edit business calendars' },
  { key: 'business-calendar.delete', module: 'BUSINESS_CALENDAR', action: 'DELETE', description: 'Delete business calendars' },
  // ── LMS — Learning Management System ─────────────────
  { key: 'lms_course.read',       module: 'LMS', action: 'READ',    description: 'View LMS courses' },
  { key: 'lms_course.write',      module: 'LMS', action: 'WRITE',   description: 'Author / edit / version courses, modules, lessons, content' },
  { key: 'lms_course.publish',    module: 'LMS', action: 'APPROVE', description: 'Approve & publish a course version (e-sign)' },
  { key: 'lms_assessment.read',   module: 'LMS', action: 'READ',    description: 'View exams / quizzes' },
  { key: 'lms_assessment.write',  module: 'LMS', action: 'WRITE',   description: 'Create / edit exams and questions' },
  { key: 'lms_assessment.grade',  module: 'LMS', action: 'UPDATE',  description: 'Manually grade descriptive answers' },
  { key: 'lms_enrollment.read',   module: 'LMS', action: 'READ',    description: 'View enrollments / assignments' },
  { key: 'lms_enrollment.assign', module: 'LMS', action: 'CREATE',  description: 'Assign courses to users / roles / departments / sites' },
  { key: 'lms_matrix.read',       module: 'LMS', action: 'READ',    description: 'View the training matrix' },
  { key: 'lms_matrix.write',      module: 'LMS', action: 'WRITE',   description: 'Configure training-matrix rules and run sync' },
  { key: 'lms_session.read',      module: 'LMS', action: 'READ',    description: 'View classroom / instructor-led sessions' },
  { key: 'lms_session.write',     module: 'LMS', action: 'WRITE',   description: 'Schedule sessions and mark attendance' },
  { key: 'lms_report.read',       module: 'LMS', action: 'READ',    description: 'View LMS compliance dashboards & exports' },
  { key: 'lms_my.read',           module: 'LMS', action: 'READ',    description: 'Access "My Learning" (assigned courses, catalog, certificates)' },
];
